title: Lucian MOCAN
description: Your role and description
url: "https://lucianmocan.github.io"
baseurl: ""
permalink: /blog/:title/
sass:
  load_paths:
    - assets/css/_sass
  style: compressed

# Basic site structure
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "songs"
    values:
      layout: "song"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

# Collections
collections:
  songs:
    output: true
    permalink: /songs/:title/
  projects:
    output: true
    permalink: /projects/:title/

# Social links
social:
  twitter: yourusername
  github: yourusername
  email: you@example.com

plugins:
  - jekyll-seo-tag